// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdM8cmY7v9wP6La8MfXlnVIoQGsNx31JM',
    appId: '1:336916779483:web:82910675867155c03917fe',
    messagingSenderId: '336916779483',
    projectId: 'freeluchapp',
    authDomain: 'freeluchapp.firebaseapp.com',
    storageBucket: 'freeluchapp.firebasestorage.app',
    measurementId: 'G-FH7J2KYWK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEaILU1yZtC6Dwoygimth7M_DhEeKwe2U',
    appId: '1:336916779483:android:90064548a92c21cc3917fe',
    messagingSenderId: '336916779483',
    projectId: 'freeluchapp',
    storageBucket: 'freeluchapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhGctg3EVDDbPH_AiKXQUTZmoHsfTT-a4',
    appId: '1:336916779483:ios:c68d653bad58a2913917fe',
    messagingSenderId: '336916779483',
    projectId: 'freeluchapp',
    storageBucket: 'freeluchapp.firebasestorage.app',
    iosBundleId: 'com.example.freeluchapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhGctg3EVDDbPH_AiKXQUTZmoHsfTT-a4',
    appId: '1:336916779483:ios:c68d653bad58a2913917fe',
    messagingSenderId: '336916779483',
    projectId: 'freeluchapp',
    storageBucket: 'freeluchapp.firebasestorage.app',
    iosBundleId: 'com.example.freeluchapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdM8cmY7v9wP6La8MfXlnVIoQGsNx31JM',
    appId: '1:336916779483:web:6618c07837b70f243917fe',
    messagingSenderId: '336916779483',
    projectId: 'freeluchapp',
    authDomain: 'freeluchapp.firebaseapp.com',
    storageBucket: 'freeluchapp.firebasestorage.app',
    measurementId: 'G-CE1X8L5PWZ',
  );
}
